version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=gvOIqn8DJ8tvHz%!
      - MONGODB_DATABASE=covi

  illness-api:
    build: ./backend/api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  illness-ui:
    build: ./frontend/app
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
    driver: local
